name: Generate Status Badges

on:
  workflow_dispatch:   # 可以手動觸發
  push:
    branches:
      - main

jobs:
  badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate badges list
        run: |
          REPO=$GITHUB_REPOSITORY
          echo "<!--START_SECTION:badges-->" > badges.txt
          for wf in .github/workflows/*.yml; do
            file=$(basename $wf)
            wf_name=$(yq e '.name' $wf)   # 抓取 workflow 裡的 name 欄位
            echo "![${wf_name}](https://github.com/${REPO}/actions/workflows/${file}/badge.svg)" >> badges.txt
          done
          echo "<!--END_SECTION:badges-->" >> badges.txt


      - name: Update README with badges
        run: |
          START="<!--START_SECTION:badges-->"
          END="<!--END_SECTION:badges-->"
          CONTENT="$(cat badges.txt)"

          awk -v start="$START" -v end="$END" -v content="$CONTENT" '
            BEGIN { inblock=0 }
            {
              if ($0 ~ start) {
                print start
                print content
                inblock=1
                next
              }
              if ($0 ~ end) {
                print end
                inblock=0
                next
              }
              if (!inblock) {
                print $0
              }
            }
          ' README.md > README.new && mv README.new README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update status badges in README"
