name: Generate Status Badges

on:
  workflow_dispatch:   # 可以手動觸發
  push:
    branches:
      - main

jobs:
  badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate badges list
        run: |
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.repository }}

          echo "<!--START_SECTION:badges-->" > badges.txt
          for wf in .github/workflows/*.yml; do
            file=$(basename $wf)
            name=$(basename $wf .yml)
            echo "![${name}](https://github.com/${GITHUB_REPOSITORY}/actions/workflows/${file}/badge.svg)" >> badges.txt
          done
          echo "<!--END_SECTION:badges-->" >> badges.txt

      - name: Update README with badges
        run: |
          perl -0777 -pi -e "s/<!--START_SECTION:badges-->.*<!--END_SECTION:badges-->/$(cat badges.txt)/s" README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update status badges in README"
